/**
 * The permission-diff human checkpoint (CLAUDE.md), made mechanical.
 *
 * Renders each demo vertical's permission surface — key → description → which
 * roles hold it — into a checked-in `demos/<name>/PERMISSIONS.md`. CI re-emits
 * with `--check` and fails on drift, so an agent that widens a role must show it
 * in the PR diff rather than in a console nobody opens.
 *
 * It reads the SAME objects the running host does: each vertical exports
 * `MODULES` (what `buildHost` registers) and `ROLES` (what `seed` defines), so
 * the artifact cannot drift from what is actually enforced. That is
 * `tools/boundary-lint.mjs`'s principle — the repo checks itself with the code
 * it ships — applied to permissions.
 *
 * Nothing here boots a host. Roles are tenant-agnostic constants and manifests
 * are exported consts, so the whole artifact is a pure function of code. That is
 * also why it is deterministic: no ULID, timestamp, or path can reach the output
 * because none is ever read.
 *
 * Exit codes follow boundary-lint's: 0 = fine, 1 = drift (the checkpoint firing),
 * 2 = the tool could not do its job. A checkpoint that checked nothing must never
 * print a green light.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

// Structural shapes — deliberately not imported from the kernel. The tool needs
// four fields, and depending on the packages it inspects would be a cycle.
interface PermissionDecl {
  key: string;
  description: string;
}
interface ModuleLike {
  manifest: { id: string; permissions: PermissionDecl[] };
}
interface RoleLike {
  key: string;
  permissions: string[];
}
interface EntityGrantLike {
  entityType: string;
  permissions: string[];
}
interface VerticalSource {
  MODULES?: ModuleLike[];
  ROLES?: RoleLike[];
  ENTITY_GRANTS?: EntityGrantLike[];
}

const root = new URL('..', import.meta.url).pathname;
const check = process.argv.includes('--check');

/** Exit 2: the tool cannot do its job. Always names the remedy. */
function cannot(message: string): never {
  console.error(`permission-diff: ${message}\n`);
  process.exit(2);
}

const byKey = <T extends { key: string }>(a: T, b: T) => a.key.localeCompare(b.key);
const sorted = (keys: string[]) => [...keys].sort((a, b) => a.localeCompare(b));
const code = (s: string) => `\`${s}\``;

function render(name: string, pkg: string, src: VerticalSource): string {
  const modules = src.MODULES ?? [];
  const roles = [...(src.ROLES ?? [])].sort(byKey);
  const grants = [...(src.ENTITY_GRANTS ?? [])].sort((a, b) =>
    a.entityType.localeCompare(b.entityType),
  );

  // The registry: every key a registered manifest declares.
  const declaredBy = new Map<string, { description: string; modules: string[] }>();
  for (const m of modules) {
    for (const p of m.manifest.permissions) {
      const seen = declaredBy.get(p.key);
      if (seen) seen.modules.push(m.manifest.id);
      else declaredBy.set(p.key, { description: p.description, modules: [m.manifest.id] });
    }
  }
  if (declaredBy.size === 0) {
    cannot(
      `demos/${name} registers ${modules.length} module(s) declaring zero permissions.\n` +
        `  A permission snapshot over an empty registry is a green light over nothing.\n` +
        `  Remedy: check that MODULES in demos/${name}/src/seed.ts is the array buildHost registers.`,
    );
  }

  // Orphans: a role or grant citing a key no manifest declares. Today this fails
  // nowhere — the check just silently denies, forever. Here it is exit 2.
  const orphans: string[] = [];
  for (const r of roles) {
    for (const p of r.permissions) {
      if (!declaredBy.has(p)) orphans.push(`role ${code(r.key)} → ${code(p)}`);
    }
  }
  for (const g of grants) {
    for (const p of g.permissions) {
      if (!declaredBy.has(p)) orphans.push(`grant on ${code(g.entityType)} → ${code(p)}`);
    }
  }
  if (orphans.length) {
    cannot(
      `demos/${name} references ${orphans.length} permission key(s) no registered manifest declares:\n` +
        orphans.map((o) => `    ${o}`).join('\n') +
        `\n\n  A check against an undeclared key denies silently at runtime, forever — it never\n` +
        `  throws, so no test catches it. Fix the typo, or declare the key in the owning\n` +
        `  module's manifest.`,
    );
  }

  const holders = new Map<string, string[]>();
  for (const r of roles) for (const p of r.permissions) holders.set(p, [...(holders.get(p) ?? []), r.key]);

  const registry = [...declaredBy.entries()].map(([key, v]) => ({ key, ...v })).sort(byKey);
  const out: string[] = [];

  out.push(
    `<!-- GENERATED by tools/permission-diff.mts — do not edit by hand.`,
    `     Regenerate: pnpm lint:permissions`,
    `     HUMAN CHECKPOINT (CLAUDE.md): an agent may never self-approve a change to this`,
    `     file. Reviewer: §3 is the risk surface — a key gaining a role. -->`,
    ``,
    `# Permission snapshot — ${pkg}`,
    ``,
    `${registry.length} keys · ${modules.length} modules · ${roles.length} roles`,
    ``,
    `## 1. Registry — every key a registered manifest declares`,
    ``,
    `| Key | Description | Declared by |`,
    `| --- | --- | --- |`,
    ...registry.map((r) => `| ${code(r.key)} | ${r.description} | ${r.modules.map(code).join(', ')} |`),
    ``,
    `## 2. Roles — as defined by this vertical's provisioning code`,
    ``,
    `Identical in every tenant. Per-tenant customisation is a runtime concern.`,
    ``,
    `| Role | Permissions |`,
    `| --- | --- |`,
    ...roles.map((r) => `| ${code(r.key)} | ${sorted(r.permissions).map(code).join(', ')} |`),
    ``,
    `## 3. Coverage — which roles hold each key`,
    ``,
    `| Key | Held by |`,
    `| --- | --- |`,
    ...registry.map((r) => {
      const held = holders.get(r.key);
      return `| ${code(r.key)} | ${held ? sorted(held).map(code).join(', ') : '— no role —'} |`;
    }),
    ``,
  );

  if (grants.length) {
    out.push(
      `## 4. Entity-narrowed grant shapes`,
      ``,
      `Reachable WITHOUT a role, narrowed to one entity per principal. A key held by`,
      `no role in §3 but listed here is deliberate, not a gap.`,
      ``,
      `| Entity type | Permissions granted per entity |`,
      `| --- | --- |`,
      ...grants.map((g) => `| ${code(g.entityType)} | ${sorted(g.permissions).map(code).join(', ')} |`),
      ``,
    );
  }

  out.push(
    `## ${grants.length ? 5 : 4}. Not covered by this artifact`,
    ``,
    `- **The grants themselves** — per-principal, per-entity, minted at runtime with`,
    `  random ULIDs. Only their shapes above are representable deterministically.`,
    `- **Operator-defined roles** — roles created against a live deployment. This`,
    `  artifact covers provisioning code only.`,
    ``,
  );
  return out.join('\n');
}

const demosDir = join(root, 'demos');
const names = readdirSync(demosDir)
  .filter((n) => statSync(join(demosDir, n)).isDirectory() && existsSync(join(demosDir, n, 'src/seed.ts')))
  .sort();

if (names.length === 0) cannot(`no demo vertical has a src/seed.ts under ${demosDir}.`);

const drifted: string[] = [];
for (const name of names) {
  const pkgPath = join(demosDir, name, 'package.json');
  const pkg = (JSON.parse(readFileSync(pkgPath, 'utf8')) as { name?: string }).name ?? `demos/${name}`;

  const mod = (await import(pathToFileURL(join(demosDir, name, 'src/seed.ts')).href)) as VerticalSource;
  // The vacuity plug: a vertical that exports neither would be silently skipped,
  // and CI would go green over a permission surface nobody reviewed.
  if (!mod.MODULES || !mod.ROLES) {
    cannot(
      `demos/${name}/src/seed.ts exports ${!mod.MODULES ? 'no MODULES' : 'no ROLES'}.\n` +
        `  Without it this vertical is skipped and CI goes green over a permission surface\n` +
        `  nobody reviewed — worse than having no checkpoint at all.\n` +
        `  Remedy: export the array buildHost registers as MODULES, and the role table\n` +
        `  seed defines as ROLES. See demos/callout/src/seed.ts.`,
    );
  }

  const content = render(name, pkg, mod);
  const artifact = join(demosDir, name, 'PERMISSIONS.md');

  if (!check) {
    writeFileSync(artifact, content);
    continue;
  }
  if (!existsSync(artifact)) {
    cannot(
      `demos/${name}/PERMISSIONS.md does not exist.\n` +
        `  A missing artifact is a broken setup, not drift.\n` +
        `  Remedy: pnpm lint:permissions && git add demos/${name}/PERMISSIONS.md`,
    );
  }
  if (readFileSync(artifact, 'utf8') !== content) drifted.push(name);
}

if (drifted.length) {
  console.error(`permission-diff: ${drifted.length} snapshot(s) out of date\n`);
  for (const n of drifted) console.error(`  ✗ demos/${n}/PERMISSIONS.md`);
  console.error(
    `\n  The permission surface changed and the checkpoint was not regenerated.\n` +
      `  Run: pnpm lint:permissions — then READ the diff. Someone must approve it.\n`,
  );
  process.exit(1);
}

console.log(
  check
    ? `permission-diff: ${names.length} snapshot(s) match`
    : `permission-diff: wrote ${names.length} snapshot(s)`,
);
